"""
Stevenson High School Summer 2026 — manually curated course data.

The summer school PDF uses a two-column layout that causes automated
extraction to merge adjacent courses and lose codes/prerequisites.
Since there are only ~35 courses and they change annually, a manual
data file is more reliable than fighting the PDF parser.

Source: data/SHSSummerSchool202632026INTERACTIVE.pdf (pages 8-19)
"""

SUMMER_COURSES_2026 = [
    # ── Applied Arts ──────────────────────────────────────────────────
    {
        "code": "D/E21S",
        "all_codes": ["D/E21S", "D/E22S"],
        "name": "Driver Education",
        "division": "Applied Arts",
        "department": "Driver Education",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "CP",
        "grade_levels": [10, 11, 12],
        "semesters_offered": [-2, -1],
        "gpa_waiver": False,
        "prerequisite_text": "Age 15 before first day, parental consent, instruction permit, 8+ credits in previous two semesters",
        "cost": "425",
    },
    {
        "code": "BUS71S",
        "all_codes": ["BUS71S", "BUS72S"],
        "name": "Introduction to Business",
        "division": "Applied Arts",
        "department": "Business Education",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "CP",
        "grade_levels": [9, 10, 11, 12],
        "semesters_offered": [-2, -1],
        "gpa_waiver": True,
        "prerequisite_text": None,
        "cost": "425",
    },
    {
        "code": "BUS12S",
        "all_codes": ["BUS12S"],
        "name": "Business Applications and Technology 1",
        "division": "Applied Arts",
        "department": "Business Education",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "CP",
        "grade_levels": [9, 10, 11, 12],
        "semesters_offered": [-1],
        "gpa_waiver": True,
        "prerequisite_text": None,
        "cost": "425",
    },

    # ── Career Exploration ────────────────────────────────────────────
    {
        "code": "CAR53S",
        "all_codes": ["CAR53S"],
        "name": "Careers in Business",
        "division": "Student Learning Programs",
        "department": "Career Exploration",
        "credit_value": 0.5,
        "duration": "semester",
        "credit_type": "Pass/Fail",
        "grade_levels": [10, 11, 12],
        "semesters_offered": [-2],
        "gpa_waiver": False,
        "prerequisite_text": None,
        "cost": "225",
    },
    {
        "code": "CAR35S",
        "all_codes": ["CAR35S"],
        "name": "Careers in Law",
        "division": "Student Learning Programs",
        "department": "Career Exploration",
        "credit_value": 0.5,
        "duration": "semester",
        "credit_type": "Pass/Fail",
        "grade_levels": [10, 11, 12],
        "semesters_offered": [-2],
        "gpa_waiver": False,
        "prerequisite_text": None,
        "cost": "225",
    },
    {
        "code": "CAR31S",
        "all_codes": ["CAR31S", "CAR33S"],
        "name": "Careers in Healthcare and Medicine",
        "division": "Student Learning Programs",
        "department": "Career Exploration",
        "credit_value": 0.5,
        "duration": "semester",
        "credit_type": "Pass/Fail",
        "grade_levels": [10, 11, 12],
        "semesters_offered": [-2],
        "gpa_waiver": False,
        "prerequisite_text": None,
        "cost": "225",
    },
    {
        "code": "CAR62S",
        "all_codes": ["CAR62S"],
        "name": "Careers in STEM",
        "division": "Student Learning Programs",
        "department": "Career Exploration",
        "credit_value": 0.5,
        "duration": "semester",
        "credit_type": "Pass/Fail",
        "grade_levels": [10, 11, 12],
        "semesters_offered": [-1],
        "gpa_waiver": False,
        "prerequisite_text": None,
        "cost": "225",
    },

    # ── Communication Arts ────────────────────────────────────────────
    {
        "code": "ENG51S",
        "all_codes": ["ENG51S", "ENG53S", "ENG55S", "ENG54S", "ENG56S"],
        "name": "College Essay Workshop",
        "division": "Communication Arts",
        "department": "English",
        "credit_value": 0.0,
        "duration": "semester",
        "credit_type": "Pass/Fail",
        "grade_levels": [11, 12],
        "semesters_offered": [-2, -1],
        "gpa_waiver": False,
        "prerequisite_text": None,
        "cost": "100",
    },
    {
        "code": "ENG25S",
        "all_codes": ["ENG25S"],
        "name": "English Failure Credit Recovery",
        "division": "Communication Arts",
        "department": "English",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "CP",
        "grade_levels": [10, 11, 12],
        "semesters_offered": [-2],
        "gpa_waiver": False,
        "prerequisite_text": "Prior enrollment in Freshman, Sophomore, Junior and/or Senior English",
        "cost": "425",
    },
    {
        "code": "ENG71S",
        "all_codes": ["ENG71S"],
        "name": "Reading for College",
        "division": "Communication Arts",
        "department": "English",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "CP",
        "grade_levels": [10, 11, 12],
        "semesters_offered": [-2],
        "gpa_waiver": False,
        "prerequisite_text": None,
        "cost": "425",
    },
    {
        "code": "ENG57S",
        "all_codes": ["ENG57S"],
        "name": "Creative Writing",
        "division": "Communication Arts",
        "department": "English",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "CP",
        "grade_levels": [11, 12],
        "semesters_offered": [-2],
        "gpa_waiver": False,
        "prerequisite_text": None,
        "cost": "425",
    },

    # ── Computer Science ──────────────────────────────────────────────
    {
        "code": "CSC61S",
        "all_codes": ["CSC61S"],
        "name": "Computer Programming 1",
        "division": "Computer Science, Engineering and Technology",
        "department": "Computer Science",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "CP",
        "grade_levels": [9, 10, 11, 12],
        "semesters_offered": [-2],
        "gpa_waiver": True,
        "prerequisite_text": None,
        "cost": "425",
    },
    {
        "code": "CSC82S",
        "all_codes": ["CSC82S"],
        "name": "Computer Programming 2",
        "division": "Computer Science, Engineering and Technology",
        "department": "Computer Science",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "CP",
        "grade_levels": [9, 10, 11, 12],
        "semesters_offered": [-1],
        "gpa_waiver": True,
        "prerequisite_text": "Computer Programming 1 (CSC161/162) or Web Development 2 (TEC281/282) or Principles of Engineering (TEC301/302) or AP Computer Science Principles (CSC371/372)",
        "cost": "425",
    },

    # ── Fine Arts ─────────────────────────────────────────────────────
    {
        "code": "ART11S",
        "all_codes": ["ART11S", "ART12S"],
        "name": "Art and Design",
        "division": "Fine Arts",
        "department": "Visual Arts",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "CP",
        "grade_levels": [9, 10, 11, 12],
        "semesters_offered": [-2, -1],
        "gpa_waiver": True,
        "prerequisite_text": None,
        "cost": "425",
    },
    {
        "code": "ART31S",
        "all_codes": ["ART31S", "ART32S"],
        "name": "Photography 1",
        "division": "Fine Arts",
        "department": "Visual Arts",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "CP",
        "grade_levels": [9, 10, 11, 12],
        "semesters_offered": [-2, -1],
        "gpa_waiver": True,
        "prerequisite_text": None,
        "cost": "425",
    },
    {
        "code": "ART51S",
        "all_codes": ["ART51S", "ART52S"],
        "name": "Digital Art and Design 1",
        "division": "Fine Arts",
        "department": "Visual Arts",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "CP",
        "grade_levels": [9, 10, 11, 12],
        "semesters_offered": [-2, -1],
        "gpa_waiver": True,
        "prerequisite_text": None,
        "cost": "425",
    },
    {
        "code": "THR11S",
        "all_codes": ["THR11S"],
        "name": "Theatre Arts",
        "division": "Fine Arts",
        "department": "Theatre",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "CP",
        "grade_levels": [9, 10, 11, 12],
        "semesters_offered": [-2],
        "gpa_waiver": True,
        "prerequisite_text": None,
        "cost": "425",
    },

    # ── Mathematics ───────────────────────────────────────────────────
    {
        "code": "MTH15S",
        "all_codes": ["MTH15S", "MTH16S"],
        "name": "Algebra 1",
        "division": "Mathematics",
        "department": "Mathematics",
        "credit_value": 1.0,
        "duration": "full_year",
        "credit_type": "CP",
        "grade_levels": [9, 10, 11, 12],
        "semesters_offered": [-2, -1],
        "gpa_waiver": False,
        "prerequisite_text": "Algebra 1 (MTH151/152)",
        "cost": "425",
    },
    {
        "code": "MTH25S",
        "all_codes": ["MTH25S", "MTH26S"],
        "name": "Geometry",
        "division": "Mathematics",
        "department": "Mathematics",
        "credit_value": 1.0,
        "duration": "full_year",
        "credit_type": "CP",
        "grade_levels": [10, 11, 12],
        "semesters_offered": [-2, -1],
        "gpa_waiver": False,
        "prerequisite_text": "Approval of Director and completion of Algebra 1 (MTH151/152)",
        "cost": "425",
    },
    {
        "code": "MTH51S",
        "all_codes": ["MTH51S", "MTH52S"],
        "name": "Algebra 2",
        "division": "Mathematics",
        "department": "Mathematics",
        "credit_value": 1.0,
        "duration": "full_year",
        "credit_type": "CP",
        "grade_levels": [10, 11, 12],
        "semesters_offered": [-2, -1],
        "gpa_waiver": False,
        "prerequisite_text": "Algebra 2 (MTH351/352)",
        "cost": "425",
    },
    {
        "code": "MTH37S",
        "all_codes": ["MTH37S", "MTH38S"],
        "name": "Algebra 2 AB/BC",
        "division": "Mathematics",
        "department": "Mathematics",
        "credit_value": 1.0,
        "duration": "full_year",
        "credit_type": "CP",
        "grade_levels": [10, 11, 12],
        "semesters_offered": [-2, -1],
        "gpa_waiver": False,
        "prerequisite_text": "Approval of Director and completion of Geometry AB/BC (MTH271/272)",
        "cost": "425",
    },

    # ── Multilingual Learning ─────────────────────────────────────────
    {
        "code": "ELD11S",
        "all_codes": ["ELD11S"],
        "name": "ELD Skills in Focus: Oracy and Literacy",
        "division": "Multilingual Learning",
        "department": "ELD",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "Pass/Fail",
        "grade_levels": [9, 10, 11, 12],
        "semesters_offered": [-2],
        "gpa_waiver": False,
        "prerequisite_text": "Multilingual Advanced Literature or Language (ELL361/362 or ELL371/372) or ELD World and Contemporary Literature (ELL461/462)",
        "cost": "225",
    },
    {
        "code": "ELD21S",
        "all_codes": ["ELD21S"],
        "name": "ELD English Enrichment",
        "division": "Multilingual Learning",
        "department": "ELD",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "Pass/Fail",
        "grade_levels": [9, 10, 11, 12],
        "semesters_offered": [-2],
        "gpa_waiver": False,
        "prerequisite_text": "Enrollment in ELD Program (going into Intermediate or Advanced) or Approval of Director",
        "cost": "225",
    },
    {
        "code": "ELD32S",
        "all_codes": ["ELD32S"],
        "name": "ELD Study Skills",
        "division": "Multilingual Learning",
        "department": "ELD",
        "credit_value": 0.5,
        "duration": "semester",
        "credit_type": "Pass/Fail",
        "grade_levels": [9, 10, 11, 12],
        "semesters_offered": [-1],
        "gpa_waiver": False,
        "prerequisite_text": "Enrollment in ELD Program or Approval of Director",
        "cost": "100",
    },

    # ── Physical Welfare ──────────────────────────────────────────────
    {
        "code": "PED21S",
        "all_codes": ["PED21S", "PED22S"],
        "name": "Health Education",
        "division": "Physical Welfare",
        "department": "Physical Education",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "CP",
        "grade_levels": [10],
        "semesters_offered": [-2, -1],
        "gpa_waiver": False,
        "prerequisite_text": None,
        "cost": "425",
    },

    # ── Science ───────────────────────────────────────────────────────
    {
        "code": "SCI21S",
        "all_codes": ["SCI21S"],
        "name": "Astronomy",
        "division": "Science",
        "department": "Science",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "CP",
        "grade_levels": [10, 11, 12],
        "semesters_offered": [-2],
        "gpa_waiver": True,
        "prerequisite_text": "Successful completion of one year of high school science",
        "cost": "425",
    },
    {
        "code": "SCI31S",
        "all_codes": ["SCI31S", "SCI33S"],
        "name": "Introduction to Biotechnology",
        "division": "Science",
        "department": "Science",
        "credit_value": 0.5,
        "duration": "semester",
        "credit_type": "Pass/Fail",
        "grade_levels": [9, 10, 11, 12],
        "semesters_offered": [-2],
        "gpa_waiver": False,
        "prerequisite_text": None,
        "cost": "225",
    },

    # ── Social Studies ────────────────────────────────────────────────
    {
        "code": "SOC13S",
        "all_codes": ["SOC13S", "SOC14S"],
        "name": "World History and Geography",
        "division": "Social Studies",
        "department": "Social Studies",
        "credit_value": 1.0,
        "duration": "full_year",
        "credit_type": "CP",
        "grade_levels": [9, 10, 11, 12],
        "semesters_offered": [-2, -1],
        "gpa_waiver": False,
        "prerequisite_text": None,
        "cost": "425",
    },
    {
        "code": "SOC41S",
        "all_codes": ["SOC41S", "SOC42S"],
        "name": "U.S. History",
        "division": "Social Studies",
        "department": "Social Studies",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "CP",
        "grade_levels": [12],
        "semesters_offered": [-2],
        "gpa_waiver": False,
        "prerequisite_text": None,
        "cost": "425",
    },
    {
        "code": "SOC33S",
        "all_codes": ["SOC33S", "SOC34S"],
        "name": "U.S. Government",
        "division": "Social Studies",
        "department": "Social Studies",
        "credit_value": 1.0,
        "duration": "full_year",
        "credit_type": "CP",
        "grade_levels": [11, 12],
        "semesters_offered": [-2, -1],
        "gpa_waiver": False,
        "prerequisite_text": None,
        "cost": "425",
    },
    {
        "code": "SOC43S",
        "all_codes": ["SOC43S", "SOC44S"],
        "name": "Economics",
        "division": "Social Studies",
        "department": "Social Studies",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "CP",
        "grade_levels": [11, 12],
        "semesters_offered": [-2, -1],
        "gpa_waiver": False,
        "prerequisite_text": None,
        "cost": "425",
    },

    # ── Special Education ─────────────────────────────────────────────
    {
        "code": "IEN51S",
        "all_codes": ["IEN51S", "IEN52S"],
        "name": "Reading and Writing for Stevenson",
        "division": "Special Education",
        "department": "Special Education",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "CP",
        "grade_levels": [9],
        "semesters_offered": [-2, -1],
        "gpa_waiver": True,
        "prerequisite_text": "Special Education Identification and Approval of Director",
        "cost": "425",
    },
    {
        "code": "IJOB2S",
        "all_codes": ["IJOB2S"],
        "name": "Preparing for Life",
        "division": "Special Education",
        "department": "Special Education",
        "credit_value": 1.0,
        "duration": "semester",
        "credit_type": "CP",
        "grade_levels": [9, 10, 11, 12],
        "semesters_offered": [-1],
        "gpa_waiver": False,
        "prerequisite_text": "Special Education Identification and Approval of Director",
        "cost": "425",
    },

    # ── Student Services ──────────────────────────────────────────────
    {
        "code": "TCH91S",
        "all_codes": ["TCH91S", "TCH92S"],
        "name": "Keys to Success",
        "division": "Student Services",
        "department": "Student Services",
        "credit_value": 0.5,
        "duration": "semester",
        "credit_type": "Pass/Fail",
        "grade_levels": [9, 10, 11, 12],
        "semesters_offered": [-2, -1],
        "gpa_waiver": False,
        "prerequisite_text": None,
        "cost": "225",
    },

    # ── Student Learning Programs ─────────────────────────────────────
    {
        "code": "ACTPREPS",
        "all_codes": ["ACTPREPS", "ACTPREPS2"],
        "name": "ACT Preparatory Course",
        "division": "Student Learning Programs",
        "department": "Student Learning Programs",
        "credit_value": 0.0,
        "duration": "semester",
        "credit_type": "Pass/Fail",
        "grade_levels": [10, 11, 12],
        "semesters_offered": [-2, -1],
        "gpa_waiver": False,
        "prerequisite_text": None,
        "cost": "150",
    },
]
